const express = require('express');
const mongoose = require('mongoose');
const router = express.Router();
const userController=require('../controller/userController');
const companyController=require('../controller/companyController');
router.get('/user', userController.showUsers);
router.get('/user/add', userController.addNewUser);
router.post('/user', userController.newUser);
router.put('/user', userController.updateUser);
router.post('/user/edit', userController.editUsers);
router.delete('/user', userController.deleteExistingUser);
router.post('/company',companyController.addNewCompany);
router.get('/company',companyController.listOfCompany);
router.get('/company/:companyName',companyController.detailsOfCompany);
router.put('/company/:companyName',companyController.updateCompany);
router.delete('/company/:companyName',companyController.userAndCompanyDeleted);
module.exports=router;